name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy --all-targets --all-features
      - run: cargo fmt --check --all
      - run: cargo doc --no-deps

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test
      - name: Run examples
        run: |
          cargo run --example trees
      - name: Run benchmarks
        run: cargo test --all-features --examples --benches
